server:
  port: 8080

spring:
  # 数据库
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:/D:/idea-workspace/IdeaProjects/recorder/src/main/resources/h2/recorder
    username: SA
    password:
  # 客户端
  h2:
    console:
      enabled: true
      path: /h2-console
  # 模版引擎
  freemarker:
    allow-request-override: false # Whether HttpServletRequest attributes are allowed to override (hide) controller generated model attributes of the same name.
    allow-session-override: false # Whether HttpSession attributes are allowed to override (hide) controller generated model attributes of the same name.
    cache: false # Whether to enable template caching.
    charset: UTF-8 # Template encoding.
    check-template-location: true # Whether to check that the templates location exists.
    content-type: text/html # Content-Type value.
    enabled: true # Whether to enable MVC view resolution for this technology.
    expose-request-attributes: false # Whether all request attributes should be added to the model prior to merging with the template.
    expose-session-attributes: false # Whether all HttpSession attributes should be added to the model prior to merging with the template.
    expose-spring-macro-helpers: true # Whether to expose a RequestContext for use by Spring's macro library, under the name "springMacroRequestContext".
    prefer-file-system-access: true # Whether to prefer file system access for template loading. File system access enables hot detection of template changes.
    #prefix:  # Prefix that gets prepended to view names when building a URL.
    #request-context-attribute:  # Name of the RequestContext attribute for all views.
    #settings.*:  # Well-known FreeMarker keys which are passed to   s Configuration.
    suffix: .ftl # Suffix that gets appended to view names when building a URL.
    template-loader-path: classpath:/templates/ftl # Comma-separated list of template paths.
    #view-names:  # White list of view names that can be resolved.

logging:
  level.org.yuan.project.recorder: debug

