server:
  port: 8080

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:/D:/idea-workspace/IdeaProjects/recorder/src/main/resources/h2/recorder
    username: SA
    password:

logging:
  level.org.yuan.project.recorder: debug