-- 基础表
CREATE TABLE BASE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '记录标识',
    UPDATE_TIME DATETIME NOT NULL COMMENT '修改时间',
    CREATE_TIME DATETIME NOT NULL COMMENT '创建时间',
    CREATER_ID BIGINT NOT NULL COMMENT '创建用户',
    UPDATER_ID BIGINT NOT NULL COMMENT '修改用户',
    VALID TINYINT NOT NULL COMMENT '有效状态'
);

-- 任务表
CREATE TABLE TASK (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,

    PLAN_ID BIGINT NOT NULL COMMENT '计划标识',

    TITLE VARCHAR(256) NOT NULL COMMENT '任务标题',
    INTRO VARCHAR(MAX) NOT NULL COMMENT '任务简介',
    FINAL VARCHAR(MAX) NOT NULL COMMENT '任务总结',
    STATUS TINYINT NOT NULL COMMENT '任务状态',

    EXPECT_ELAPSE INT NOT NULL COMMENT '预计耗时',
    ACTUAL_ELAPSE INT NOT NULL COMMENT '实际耗时',

    EXPECT_START_TIME DATETIME NOT NULL COMMENT '预计开始时间',
    EXPECT_PAUSE_TIME DATETIME NOT NULL COMMENT '预计暂停时间',
    EXPECT_FINIS_TIME DATETIME NOT NULL COMMENT '预计结束时间',

    START_TIME DATETIME COMMENT '开始时间',
    PAUSE_TIME DATETIME COMMENT '暂停时间',
    SUBMIT_TIME DATETIME COMMENT '提交时间',
    FINISH_TIME DATETIME COMMENT '完成时间',

    UPDATE_TIME DATETIME NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    CREATER_ID BIGINT NOT NULL,
    UPDATER_ID BIGINT NOT NULL,
    VALID TINYINT NOT NULL
);

-- 耗时表
CREATE TABLE ELAPSE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,

    PLAN_ID BIGINT NOT NULL COMMENT '计划标识',
    TASK_ID BIGINT NOT NULL COMMENT '任务标识',
    STATUS TINYINT NOT NULL COMMENT '耗时状态: 0开始，1结束',

    UPDATE_TIME DATETIME NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    CREATER_ID BIGINT NOT NULL,
    UPDATER_ID BIGINT NOT NULL,
    VALID TINYINT NOT NULL
)

-- 计划表
CREATE TABLE PLAN (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,

    TITLE VARCHAR(256) NOT NULL COMMENT '计划标题',
    INTRO VARCHAR(MAX) NOT NULL COMMENT '计划简介',

    UPDATE_TIME DATETIME NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    CREATER_ID BIGINT NOT NULL,
    UPDATER_ID BIGINT NOT NULL,
    VALID TINYINT NOT NULL
)

-- 模板表
CREATE TABLE TEMPLET (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,

    TASK_PLAN_ID BIGINT NOT NULL COMMENT '计划标识',
    TASK_TITLE VARCHAR(256) NOT NULL COMMENT '任务标题',
    TASK_INTRO VARCHAR(MAX) NOT NULL COMMENT '任务简介',
    TASK_EXPECT_ELAPSE INT NOT NULL COMMENT '预计耗时',

    STATUS TINYINT NOT NULL COMMENT '模板状态',

    UPDATE_TIME DATETIME NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    CREATER_ID BIGINT NOT NULL,
    UPDATER_ID BIGINT NOT NULL,
    VALID TINYINT NOT NULL
)

-- 周期表
CREATE TABLE CYCLE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,

    TEMPLET_ID BIGINT NOT NULL COMMENT '模版标识',
    START_TIME DATETIME NOT NULL COMMENT '开始时间',
    FINIS_TIME DATETIME NOT NULL COMMENT '结束时间',
    TIME_STEP INT NOT NULL COMMENT '时间步长 - 天',

    UPDATE_TIME DATETIME NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    CREATER_ID BIGINT NOT NULL,
    UPDATER_ID BIGINT NOT NULL,
    VALID TINYINT NOT NULL
)

-- 测试表
CREATE TABLE DEMO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,

    INFO VARCHAR(256) NOT NULL,

    UPDATE_TIME DATETIME NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    CREATER_ID BIGINT NOT NULL,
    UPDATER_ID BIGINT NOT NULL,
    VALID TINYINT NOT NULL
);

