-- 基础表
CREATE TABLE BASE (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    UPDATE_TIME DATETIME NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    CREATER_ID BIGINT NOT NULL,
    UPDATER_ID BIGINT NOT NULL,
    VALID TINYINT NOT NULL
);

-- 测试表
CREATE TABLE DEMO (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,

    INFO VARCHAR(256) NOT NULL,

    UPDATE_TIME DATETIME NOT NULL,
    CREATE_TIME DATETIME NOT NULL,
    CREATER_ID BIGINT NOT NULL,
    UPDATER_ID BIGINT NOT NULL,
    VALID TINYINT NOT NULL
);